In [3]:
# import numpy
# create array x

import numpy as np

x = np.array([1,2,3,4,5])


In [4]:
# print the shape of x
print np.shape(x)

(5,)


In [69]:
# create a two dimensional array
twoD = np.array([[2,5,3,4],[6,6,7,8],[9,10,11,12]])
print twoD

[[ 2  5  3  4]
 [ 6  6  7  8]
 [ 9 10 11 12]]


In [70]:
# print shape of 2d array
print np.shape(twoD)

(3, 4)


In [71]:
# reshape the array to 2 x 6
twoD = np.reshape(twoD, (2,6))
print twoD


[[ 2  5  3  4  6  6]
 [ 7  8  9 10 11 12]]


In [72]:
# reshape the array to 1 x 12
twoD = np.reshape(twoD, (1,12))
print twoD

[[ 2  5  3  4  6  6  7  8  9 10 11 12]]


In [73]:
# transpose the array
twoD = np.transpose(twoD)

In [88]:
# find 5th val
print twoD

twoD[5-1,0]

[[ 2]
 [ 5]
 [ 3]
 [ 4]
 [ 6]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


6

In [87]:
# find 2nd to last
twoD[len(twoD) - 2,0]


11

In [116]:
# find elements 2 up to 5
print twoD[1:4,0]

[5 3 4]


[2, 5, 3, 4]


In [151]:
# 1,2,3,6
index = [0,1,2,5]
print twoD[[0,1,2,5],0]


[2 5 3 6]


In [125]:
# find values in x > 4
print twoD[twoD > 4]


[ 5  6  6  7  8  9 10 11 12]


In [158]:
# 3D array
threeD = np.reshape(twoD,(2,3,2))
print threeD
print threeD[threeD > 4]

print '5th value'
print threeD[0][2,0]

print '2nd to last'
print threeD[1][2,0]

print '2nd element to 5th element'
print np.reshape(threeD[0][1:4],(1,4))

print 'elements 1,2,3,6' # gave up on this part for now
print threeD[[0]][[0,0]]

# elements that are >4
print threeD[threeD > 4]

[[[ 2  5]
  [ 3  4]
  [ 6  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[ 5  6  6  7  8  9 10 11 12]
5th value
6
2nd to last
11
2nd element to 5th element
[[3 4 6 6]]
elements 1,2,3,6
[[[2 5]
  [3 4]
  [6 6]]

 [[2 5]
  [3 4]
  [6 6]]]
[ 5  6  6  7  8  9 10 11 12]
